### ISSUE TITLE
Question : Rendering a cshtml view

### ISSUE THREAD

**Issue by IainMNorman** [CarterCommunity/Carter#105]
Hi, I can't see any examples of such, but is it possible to render a razor/cshtml view from a Carter module?

**Comment by jchannon** [comment]
Hi,

No, Carter was originally written to be an API only library. However, I
have a package here that will use Handlebars to return html. Needs a bit of
tidying up and then it can be released.
https://github.com/CarterCommunity/Carter.HtmlNegotiator

A member of the community was going to look at the ability to use Razor but
not heard anything yet.

**Comment by IainMNorman** [comment]
Cheers Jon.

**Comment by JoeStead** [comment]
@IainMNorman I haven't touched Razor for several years, so I'm certainly out of the loop on that front, but you might be able to leverage the Razor Pages SDK in ASP.NET Core 2.1 onwards: https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/sdk?view=aspnetcore-2.1 to achieve something like this (perhaps building off the back of the HtmlNegotiator). 

If you, or anyone else, does go down this route, it could be interesting :)

**Comment by jchannon** [comment]
Also see https://github.com/toddams/RazorLight
