### ISSUE TITLE
Swagger-support?

### ISSUE THREAD

**Issue by proepkes** [CarterCommunity/Carter#124]
Does Swagger work with Carter out of the box?

**Comment by jchannon** [comment]
Not out of the box but it's something in the back of my mind.

There is a feature in netcore 2.1 that didn't make the cut which might go
to help the enablement of this in Carter but I'm not sure when it's
scheduled to run.

The other option would be to make Carter routes have an input/output model
that could be decorated somehow for Swagger/OpenAPI.

You might end up with something like Get<InputModel,
OutputModel>("/products", async context => context.Response.AsJson(new
OutputModel());

If you have any thoughts or want to help implement it lets continue the
discussion here

**Comment by jchannon** [comment]
The ASP.NET Core feature was called Dispatcher but they renamed it to Global Routing. A sample is here https://github.com/aspnet/Routing/blob/release/2.2/samples/RoutingSample.Web/UseGlobalRoutingStartup.cs

Would need to see how that helps swagger though but that's what they are designing it for. Whether we can use that is another question

**Comment by damianh** [comment]
Swashbuckle uses MVC's ApiExplorer https://andrewlock.net/introduction-to-the-apiexplorer-in-asp-net-core/ . I presume this is a higher level than what Carter works at?

**Comment by jchannon** [comment]
Yeah. The API explorer has a dependency on MVC which  we don’t want :(

**Comment by damianh** [comment]
BOO!

**Comment by jchannon** [comment]
Initial spike:

```
public class CarterMetaModule<TRequest, TResponse>
{
   public Type Request { get; } => typeof(TRequest)
   public Type Respond {get; } => typeof(TResponse)
   public abstract int[] StatusCodes {get;} 
}

public class ListById : CarterMetaModule<PersonIn, PersonOut>
{
    public int[] StatusCodes => [200,401];
}

this.Get<ListById>(ctx => ctx.Response.Write("hi"))
```

**Comment by JoeStead** [comment]
Obviously a version without a `TRequest` and a version without `TResponse` and a version with neither will be required too. It will mean class-splosion for big projects, but it avoids attributes

**Comment by jeffdoolittle** [comment]
I think it's lovely and it's something I always missed with NancyFx - self-documenting routes.

**Comment by JoeStead** [comment]
If I get time tonight, I'm going to spin up a quick prototype on this, I can't see it being too much effort (famous last words). Will link the branch here later
