### ISSUE TITLE
Add RequiresRoles method

### ISSUE THREAD

**Issue by Sigvaard** [CarterCommunity/Carter#130]
Basically addition to what already exists: https://github.com/CarterCommunity/Carter/blob/5a67b19232c2b645da1dc9d42aecdaeacf1aef56/src/CarterModuleSecurity.cs#L35

**Comment by jchannon** [comment]
I think Roles is an older design pattern and Claims/permissions have won that area but I'm open to be persuaded otherwise 😄

**Comment by Sigvaard** [comment]
> I think Roles is an older design pattern and Claims/permissions have won that area

Can you elaborate more?

**Comment by jchannon** [comment]
https://stackoverflow.com/questions/22814023/role-based-access-control-rbac-vs-claims-based-access-control-cbac-in-asp-n

**Comment by Sigvaard** [comment]
It would be easier for people who would like to port to Carter from MVC if they use `[Authorize(Roles="role1,role2")]` there.

Also, I don't know if it adds any dependency to Carter but there's policy-based authorization in ASP.NET Core. So if it doesn't add any dependency it would be nice to have `RequiresPolicy` method too.

And how can you apply authorization requirement per route/action? Is this possible in Carter?

**Comment by jchannon** [comment]
Personally I feel if they still use Roles they need to update and use
Claims. For example Nancy used to do Roles but we moved to Claims.

A user can always write an extension just like RequiresClaims is in their
own codebase if needs be or a separate nuget extension package if they want.

I think there is an issue for auth per route still open, think it proved to
be tricky if i remember correctly :)

**Comment by Sigvaard** [comment]
I see. Close it if you want. Those methods are trivial to implement anyway.
