### ISSUE TITLE
CarterModule.Get() automatically registers route for both GET and HEAD verbs

### ISSUE THREAD

**Issue by aleksander-oven** [CarterCommunity/Carter#134]
I noticed this when trying to debug why I couldn't register a different handler for HEAD when GET was already registered for the same route. It's not something that I can't work around, of course, but I'm still wondering: is there a good reason why CarterModule.Get() would want to implicitly cover HEAD as well?

**Comment by aleksander-oven** [comment]
FWIW: There's no need to change anything in Carter, except for maybe the documentation. IMHO, Such peculiarities deserve a mention somewhere.

**Comment by jchannon** [comment]
Yup good point. Feel like putting it in a PR for the README?

I copied Nancy’s implementation there. Could potentially add a flag so you
can turn it off?!
