### ISSUE TITLE
Accept RouteMetaData instance

### ISSUE THREAD

**Issue by colinbate** [CarterCommunity/Carter#143]
Thanks for the OpenAPI work, it would be nice if the route could accept an instance of `RouteMetaData` as an alternative to a type name. I'm not too concerned about how that instance would get passed but I'd like to avoid the creation of new classes for each route just to document it. Kind of defeats the purpose of using Carter in the first place in my opinion.

**Comment by jchannon** [comment]
Like `Get(“/home”, new RouteMetaData{Responses = new []{..}}, async context => ....`

**Comment by heerup** [comment]
#234

**Comment by jchannon** [comment]
Carter 6  will use .NET 6 for OpenApi
