### ISSUE TITLE
Method not allowed when having two routes differing only by verb and parameter name

### ISSUE THREAD

**Issue by wastaz** [CarterCommunity/Carter#145]
If I have two routes that differ only by verb and by the name of one or more of the parameters in the route, then it seems like carter will overwrite all routes except the last.

For example, in the module below if you try to call `GET /test/42/blah/d9796528-4631-44e2-b898-6caf2706467d` then you will get `405 method not allowed`. However `PUT /test/42/blah/d9796528-4631-44e2-b898-6caf2706467d` will work with a `200 OK` and the expected response body.

If you rename the `other1` and `other2` parameter in the route, the both the `GET` and `PUT` routes will work as expected.

```

    public class TestModule : CarterModule
    {
        public TestModule()
        {

            Put("/test/{id:int}/blah/{otherid1:guid}", async (request, response, route) =>
            {
                var id = route.As<int>("id");
                var otherid = route.As<Guid>("otherid1");

                response.StatusCode = (int) HttpStatusCode.OK;
                await response.AsJson(new
                {
                    Id = id,
                    Other = otherid,
                    Method = "Put"
                });
            });
            
            Get("/test/{id:int}/blah/{otherid2:guid}", async (request, response, route) =>
            {
                var id = route.As<int>("id");
                var otherid = route.As<Guid>("otherid2");

                response.StatusCode = (int) HttpStatusCode.OK;
                await response.AsJson(new
                {
                    Id = id,
                    Other = otherid,
                    Method = "Get"
                });
            });
        }
    }
```

**Comment by jchannon** [comment]
It must be failing here somehow if that's the case
https://github.com/CarterCommunity/Carter/blob/master/src/CarterExtensions.cs#L73

However I'd expect the tests to fail here for different verbs
https://github.com/CarterCommunity/Carter/blob/master/test/Carter.Tests/TestModule.cs#L74
unless with extra route constraints etc it is an issue.

Probably best to write a test to see if it fails

**Comment by jchannon** [comment]
Hi, have started looking at this however I saw the opposite of what you said, when they both have the same `other1` routes both work. If the GET has `other2` and PUT has `other1` and I issue a GET I get a 405

**Comment by davidfowl** [comment]
cc @JamesNK @rynowak

**Comment by JamesNK** [comment]
Routing doesn't care about the name when matching. How could it? The parameter name is just the name the route value is given when the route has matched.

IRouter routing doesn't have any built in logic for the HTTP method.

**Comment by jchannon** [comment]
`"IRouter routing doesn't have any built in logic for the HTTP method."`

What do you mean here, there are MapVerb and MapPost etc when you use those it doesn't take into account the verb when deciding which route to execute?

**Comment by rynowak** [comment]
`IRouter` has a simpler priority system - the routes run in the order you specified them and the first match wins. If your example a few comments up based on `IRouter` changed the order of the routes to have `"HEAD"` first, then that's what would be returned.

Since endpoint routing gets data from a variety of sources, we order it ourselves. There are built-in concepts like precedence (based on route template) and some of the policies apply ordering as well (a route with and HTTP method is more specific than one without). There's also an `Order` value which you can set yourself if you want things to be sequential. We use order to turn MVC conventional routes into endpoints so we can replicate the old behaviour.

**Comment by rynowak** [comment]
> "IRouter routing doesn't have any built in logic for the HTTP method."

> What do you mean here, there are MapVerb and MapPost etc when you use those it doesn't take into account the verb when deciding which route to execute?

Yeah @JamesNK is just wrong 😆. Those features aren't used by MVC, but they do exist.

**Comment by JamesNK** [comment]
Ah, ok. I've never seen the IRouter HTTP method matching.

**Comment by jchannon** [comment]
I've raised something with ER on one of the aspnet repos and discussed it with @JamesNK but now I can't find it (it was a PR he did for a sample third party fwk you guys have I think to test ER) hopefully it won't be much of a change for Carter but if you could point me in the right direction for package feeds etc I could start to look to move it over

**Comment by JamesNK** [comment]
https://github.com/davidfowl/Web.Framework/pull/6

It's a little crusty. I should update it for preview 1. Names might be slightly different but the concepts haven't changed.

**Comment by JamesNK** [comment]
https://github.com/aspnet/AspNetCore/issues/4221

**Comment by jchannon** [comment]
Ah brill!

Thanks for the help, pointers and transparency

**Comment by jchannon** [comment]
Just out of interest is there a list of routes eg verbs and templates in the routing middleware or part of the httpcontext that is accessible currently so I can see what routes the fwk knows about?

**Comment by jchannon** [comment]
Guess this is it?https://stackoverflow.com/a/50696890

**Comment by jchannon** [comment]
Or easier https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.routing.routebuilder.routes

**Comment by jchannon** [comment]
@wastaz @JamesNK @rynowak this issue can be closed once ASP.NET Core 3 is released. I have moved Carter to ASP.NET Core 3 on this branch https://github.com/CarterCommunity/Carter/pull/149 and the work there resolves this issue.

@JamesNK @rynowak it seemed relatively straight forward to move to the new routing I feel I have missed something! Are there planned blog posts etc on what else can be done with the new routing? One thing I noticed in the nightlies was a `UseEndpoint()` which I thought I needed but didn't but also couldn't really see what it did. Just wondering if I could improve Carter more but don't know what else the routing brings, like I don't really understand the datasources is and the params object[] metadata arguments are but thanks for the all the help so far.

This was also tweeted:
https://twitter.com/CarterLibs/status/1085248206168969216

**Comment by JamesNK** [comment]
`UseEndpoint` is middleware to explicitly run the matched endpoint. The matched endpoint gets implicitly run at the end the middleware pipeline so you don't need it.

Your PR looks good to me.

Your routes don't need a datasource because they don't change during runtime.

Metadata is stored in `Endpoint.Metadata` and can be used by systems that use endpoints. For example, `MapGet` automatically adds `IHttpMethodMetadata` to the endpoint with the GET verb. The matcher then uses that metadata to do HTTP matching.

**Comment by rynowak** [comment]
> Are there planned blog posts etc on what else can be done with the new routing?

So much this. We plan to talk about it in more detail once the details about how to wire it up are further along.

**Comment by abazanov** [comment]
Guys, I don't want to raise a new issue because it might just be me, but I am getting the same response 405 Method Not Allowed when I try...

`Get<FindSomeObjectMeta>("/{q}", async (ctx) => ...`

Where `q` is just a `string` and then I call  `[route]/?q=whatever`
