### ISSUE TITLE
Add EnableRewind option to AsString body extension

### ISSUE THREAD

**Issue by jchannon** [CarterCommunity/Carter#156]
This will need to call 👍 
```
 private static async Task PrepareRequestBody(HttpContext context)
        {
            if (!context.Request.Body.CanSeek)
            {
                context.Request.EnableBuffering();

                await context.Request.Body.DrainAsync(CancellationToken.None);
            }

            // Always start at the beginning.
            context.Request.Body.Seek(0L, SeekOrigin.Begin);
        }

```

Then read the body without a using statement in a StreamReader otherwise this closes the stream and it can't be read again therefore you'd need `new StreamReader(stream).ReadToEndAsync()`

**Comment by jchannon** [comment]
See here for usage - http://github.com/LykkeCorp/apollo/blob/e826f0ae9f79f85b1bc24ff475d185d6daa05787/src/Apollo/Features/IdentityVerification/Identity/WebhookModule.cs#L39

**Comment by 0x414c49** [comment]
@jchannon the link you provided does not exist anymore.

**Comment by jchannon** [comment]
Ah its just a link to show how you could call AsString() which will have the code above in and then you could call Bind<T> and it wouldn't fail as the body's position would be back at position 0

**Comment by jchannon** [comment]
Closing, not really an issue as we don't have Bind anymore
