### ISSUE TITLE
Please don't make CarterDiagnostics internal

### ISSUE THREAD

**Issue by gkinsman** [CarterCommunity/Carter#173]
Currently the only way to customise registrations of `CarterModule` is to not use `AddCarter`, and register everything yourself, which isn't a big deal. This isn't possible though, if something can't be registered because it's internal, like `CarterDiagnostics`. 

Given it's resolvable from the container and hence accessible by users, it's really considered part of the public API - do you think it's reasonable to keep it public?

Cheers

**Comment by jchannon** [comment]
I actually think that part of #172 we've created a mirror copy of it and might need to look to make them one class now

**Comment by jchannon** [comment]
Fixed as part of #172 - CarterDiagnostics was removed
