### ISSUE TITLE
OpenApi - support for nested objects and more datatypes

### ISSUE THREAD

**Issue by wastaz** [CarterCommunity/Carter#184]
The OpenApi stuff doesnt seem to support some datatypes. For example

```
public class Actor {
    public long Age { get; set; } // For supporting really old actors
}
```
will generated the schema as a string.

Nested objects
```
public class Dog {
    public string Name { get; set; }
}
public class Actor {
    public Dog Pet { get; set; }
}
```
will also be generated as a string.

**Comment by jchannon** [comment]
Yup this in progress in #169

**Comment by jchannon** [comment]
Feel free to pull it and have a play. Seems to cope well for most things but nested types and generics need looking at a bit more

**Comment by wastaz** [comment]
Ah great! :)

**Comment by williamhbell** [comment]
A fix was submitted last night that handles generics and nested objects.

**Comment by jchannon** [comment]
Merged some changes thanks to the fantastic @williamhbell so will close this and please open a new issue if there is a problem
