### ISSUE TITLE
Azure AD B2C JWT Authentication

### ISSUE THREAD

**Issue by abazanov** [CarterCommunity/Carter#197]
Has anyone got a good example of how to get Carter to accept a JWT from Azure AD B2C?

This is what I have so far and it is failing.

`app.UseCarter(GetOptions(new[] { Configuration["oa:basepath"] }));`

```
private CarterOptions GetOptions(ICollection<string> addresses)
        {
            var options = new OpenApiOptions(
                "Test API",
                addresses,
                new Dictionary<string, OpenApiSecurity>
                {
                    {
                        "BearerAuth",
                        new OpenApiSecurity
                        {
                            Type = OpenApiSecurityType.http,
                            Scheme = "bearer",
                            BearerFormat = "JWT",
                            Name = "Authorization",
                            In = OpenApiIn.header
                        }
                    }
                }, new[] { "BearerAuth" });

            return new CarterOptions(null, null, options);
        }
```

**Comment by jchannon** [comment]
That code has nothing to do with authentication it's just setting up metadata for the openapi generated docs.

You'll need something like `services.AddAuthentication.AddAzureFoo()`

**Comment by abazanov** [comment]
Oh, OK. Thanks @jchannon

**Comment by abazanov** [comment]
@jchannon please delete this issue then, if you can. It is just clutter.

**Comment by jchannon** [comment]
just close it and it'll be fine :)

**Comment by abazanov** [comment]
Ok, I will come straight... It was a silly question, so I want it gone :)

**Comment by jchannon** [comment]
issues can't be deleted, welcome to github :)

**Comment by abazanov** [comment]
Nowhere to hide 🤦‍♂

**Comment by abazanov** [comment]
For those who might come here in the future, here is how I got it working...

```
services.AddAuthentication(options =>
            {
                options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(jwtOptions =>
            {
                jwtOptions.Authority = "https://[tenant url]/tfp/[tenant guid]/[policy]/v2.0/";
                jwtOptions.Audience = ["ClientId"]; // Application Id
                jwtOptions.Events = new JwtBearerEvents
                {
                    OnAuthenticationFailed = AuthenticationFailed,
                    OnTokenValidated = TokenValidated
                };
            });
```

Also

`app.UseAuthentication();`

I also opted for second option in this drop-down, which made a difference.

![image](https://user-images.githubusercontent.com/5940942/60529285-33664280-9cee-11e9-9986-d8b26231c80b.png)

It took me less than a day to sort out. I hope it takes you less :)
