### ISSUE TITLE
Invalid cast from 'System.String' to 'System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.

### ISSUE THREAD

**Issue by abazanov** [CarterCommunity/Carter#198]
Fails to bind a string to bool. Blows up with the error:

Invalid cast from 'System.String' to 'System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.

![image](https://user-images.githubusercontent.com/5940942/60818474-9f84f280-a195-11e9-87d4-ed17b63e7bb4.png)

**Comment by abazanov** [comment]
If I add this:

```
// Convert.ChangeType (below) chokes on Booleans, so doing it here instead.
                    if (propertyType == typeof(bool) || propertyType == typeof(bool?))
                    {
                        if (bool.TryParse(val.Value[0], out bool result))
                        {
                            return result;
                        }
                        return false;
                    }
```
Then it works.

**Comment by jchannon** [comment]
We probably need to expand that out, Form binding wasn't really that well tested tbh. We may need to add TypeDescriptors instead. See here for example: https://www.hanselman.com/blog/TypeConvertersTheresNotEnoughTypeDescripterGetConverterInTheWorld.aspx

**Comment by abazanov** [comment]
It then goes on to fail on `DateTime?` and `int?` 😭

**Comment by abazanov** [comment]
@jchannon do you think you will get some time to do that soon, or not really?

**Comment by jchannon** [comment]
Potentially, if you need it sooner, feel free to take a crack at it :)

**Comment by abazanov** [comment]
It is stopping me from progressing. If you can't do it in the next couple of days then I will have to give it a go. Do you think in the next couple of days is doable?

**Comment by jchannon** [comment]
Probably not

**Comment by abazanov** [comment]
Ok, let me have a quick look at the link you posted. Will get back to you. Cheers.

**Comment by abazanov** [comment]
I am curious though how other people are using it currently ❓ Unless they do the binding themselves. 😕

**Comment by jchannon** [comment]
Most I imagine are using JSON bodies not forms

**Comment by abazanov** [comment]
Good point.

**Comment by abazanov** [comment]
@jchannon I will give this a miss for now. I was using Postman which makes it very easy to fire forms at an API. With JSON, you have to type it all out. My assumption was that it would make no difference. Since it does, I will stop using forms. Thanks for your help.

**Comment by jchannon** [comment]
I'll keep the issue open so it can be fixed at some point

**Comment by jchannon** [comment]
For anyone wanting to pick this up the offending code sits in this block:

https://github.com/CarterCommunity/Carter/blob/master/src/ModelBinding/BindExtensions.cs#L48

**Comment by abazanov** [comment]
If I was not running a bit late on this project, I would have. Maybe I will get some time, but for now, I don't, sorry.
