### ISSUE TITLE
OpenApi - Calling '/openapi' throws an error (NetCoreApp3.0).

### ISSUE THREAD

**Issue by stephenpope** [CarterCommunity/Carter#200]
System Info :

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview6-012264/
```

Basic web app..

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="4.2.0" />
  </ItemGroup>

</Project>
```

Simple module ..

```csharp
    public class HomeModule : CarterModule
    {
        public HomeModule()
        {
            Get<GetDefault>("/", async (req, res, routeData) =>
            {
                res.StatusCode = 409;
                await res.WriteAsync("There's no place like 127.0.0.1");
            });
        }
    }
    
    public class GetDefault : RouteMetaData
    {
        public override string Description { get; } = "A description.";

        public override RouteMetaDataResponse[] Responses { get; } =
        {
            new RouteMetaDataResponse
            {
                Code = 200,
                Description = "A response description.",
                Response = typeof(string)
            }
        };

        public override string Tag { get; } = "Basic";
    }
```

Calling `https://localhost:5001/openapi` errors with ..

```
An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Carter.OpenApi.CarterOpenApi.<>c__DisplayClass0_0.<BuildOpenApiResponse>b__0(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by jchannon** [comment]
Is it just netcore 3 SDK, works ok on 2.x?

**Comment by stephenpope** [comment]
Same error when running as NetcoreApp2.2 (still with NetCore 3 SDK installed). Have I done something wrong in my setup ?

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
```
using ..
```json
{
  "sdk": {
    "version": "2.2.300"
  }
}
```

**Comment by jchannon** [comment]
Seems ok,

Only thing I notice is netcore 3 sdk, sdk in csproj i tend to use is
withouth the .Web suffix, I don't tend to use Microsoft.AspNetCore.App
dependency either

Might be worth seeing if you can find the difference with the sample
project as that does work
https://github.com/CarterCommunity/Carter/tree/master/samples/CarterSample

**Comment by stephenpope** [comment]
The sample works ok. I will work backwards from there. It says its around L23 so it might be because I have not specified any `OpenApiOptions` but I will check now.

**Comment by stephenpope** [comment]
Right .. so I added some `CarterOptions` ..

```csharp
private CarterOptions GetOptions(ICollection<string> addresses)
        {
            return new CarterOptions(openApiOptions:
                new OpenApiOptions(documentTitle: "Carter <3 OpenApi", addresses: addresses, new Dictionary<string, OpenApiSecurity>())); 
        }
```

.. which fixed my error (Im assuming its the `OpenApiOptions` or `documentTitle` being null thats causing the failure.) but then i ran smack into the `Synchronous operation not allowed error` (https://github.com/CarterCommunity/Carter/issues/39) ... so had to add `AllowSynchronousIO` into my `Program.cs`: 

```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
  Host.CreateDefaultBuilder(args).ConfigureWebHostDefaults(webBuilder =>
  {
      webBuilder.UseStartup<Startup>().ConfigureKestrel(((context, options) =>
      {
          options.AllowSynchronousIO = true;
      }));
});
```

**Comment by jchannon** [comment]
Soooooo, just merged lots of OpenApi changes and OpenApiOptions needs supplying if you want openapi to work. Question is how to enforce that or do we leave it as is.....

**Comment by jussimattila** [comment]
I think requiring OpenApiOptions for the functionality is fine. Just need to update the docs, as it currently says: 

> Carter supports OpenApi out of the box. Simply call /openapi from your API and you will get a OpenApi JSON response.

**Comment by jchannon** [comment]
That should still be the case?

**Comment by stephenpope** [comment]
Agreeing with @jussimattila - Fine as long as the exception is more helpful than the previous one :)

**Comment by jussimattila** [comment]
Yeah, instead of `System.NullReferenceException: Object reference not set to an instance of an object.` one should see `InvalidOperationException: OpenApiOptions have not been provided to Carter."

**Comment by jchannon** [comment]
Just tested it with services.AddCarter() and app.UseEndpoints(builder =>
builder.MapCarter()); and called /openapi and no exception.


On Tue, 26 Nov 2019 at 08:27, Jussi Mattila <notifications@github.com>
wrote:
>
> Yeah, instead of System.NullReferenceException: Object reference not set
to an instance of an object. one should see `InvalidOperationException:
OpenApiOptions have not been provided to Carter."

**Comment by jussimattila** [comment]
I recently setup openapi with Carter v4.2.0. That gave the null reference error, which brought me here. Thanks @stephenpope for the fix, BTW. And sorry @jchannon for not testing with the latest bits!

**Comment by jchannon** [comment]
Ah no worries, I did a release last night and thought it was related :)

**Comment by stephenpope** [comment]
Does the call the /openapi return anything when no OpenApiOptions are specified? Glad it doesn't NullRef throw but would you want to debug log the issue or something to help nudge people towards what they are missing ? (Sorry if this seems pedantic ;)

**Comment by jchannon** [comment]
It will still return the openapi json if no options are available but some
properties like the title and server urls will be a default value

**Comment by stephenpope** [comment]
Perfect :) Thanks! Happy to close the issue then :)

**Comment by JoeStead** [comment]
:+1: glad it got sorted
