### ISSUE TITLE
Base module an DI issue

### ISSUE THREAD

**Issue by jchannon** [CarterCommunity/Carter#201]
You get a DI error when you have the following
```
 public class ApiModule : CarterModule
    {
        public ApiModule(string modulePath) : base("/api" + modulePath)
        {
        }
    }

public class FooModule : ApiModule
{
  public FooModule() : base("/foo"){}
}
```

**Comment by poke** [comment]
You could simply make the `ApiModule` abstract to avoid this.

Otherwise, how do you envision this to work? Carter will automatically look for modules and attempt to instantiate them. So when it finds `ApiModule`, it tries to create that one but fails because it cannot resolve `modulePath`.
