### ISSUE TITLE
Prettify each response

### ISSUE THREAD

**Issue by Matias-Barrios** [CarterCommunity/Carter#204]
How can I tell the framework that I want the property **Formatting.Indented** to ALL the responses?

In which file should I add this and how?

I'm using NewtonSoft JSON library.

**Comment by jchannon** [comment]
Copy paste this into your solution and add the required settings:
https://github.com/CarterCommunity/Carter/blob/master/src/DefaultJsonResponseNegotiator.cs

Carter will auto register your implementation with the IOC container

**Comment by Matias-Barrios** [comment]
Thanks!!
