### ISSUE TITLE
Logging in bind methods

### ISSUE THREAD

**Issue by jchannon** [CarterCommunity/Carter#206]
Need to add debug logging in Bind methods

**Comment by jeffdoolittle** [comment]
I'd be willing to take this on. Any further details or requirements on this @jchannon ?

**Comment by jchannon** [comment]
Great stuff!

No real requirements. Just some debug level logs when it’s working out how
to do the types etc

**Comment by jeffdoolittle** [comment]
Assign it to me and I'll get on it.
