### ISSUE TITLE
Sending image as multipart post request

### ISSUE THREAD

**Issue by Matias-Barrios** [CarterCommunity/Carter#208]
I am having a small issue where the image im sending from postman is not populated into my model when using **BindAndValidate** method.

Here is my model : 
```C#
public class Photo {
     public string date {get; set;}
     public byte[] image {get; set;} 
}
``` 

And here is my actual call :

```
curl -k -X POST \
 http://localhost:8888/upload \
 -H 'Content-Type: multipart/form-data' \
 -H 'cache-control: no-cache' \
 -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
 -F 'image=@\\LAPTOP\USERDAT01\MATIAS\Desktop\image.jpg' \
 -F date=2019-10-16
```

The problem im facing is that although *date* field on my model is actually getting populated the *image* property is always null.

This is my module code :

```C#
var request = req.BindAndValidate<Photo>();
uploadPhoto(request.data.date, request.data.image)
```

What am I doing wrong?

**Comment by jchannon** [comment]
Nothing I’m not sure we have that scenario supported.

We do have a BindFile APIs that you could look at.

You would need to call that and Bind to get your Date field populated

**Comment by Matias-Barrios** [comment]
Thanks so much for your comment, it helped me to get this. I used **BindFile** to get the actual image and **BindAndValidate** for the body.

```C#
var request = req.BindAndValidate<Photo>();
using (StreamReader reader = new StreamReader(req.BindFile().Result.OpenReadStream()))
{
      request.Data.image = Encoding.ASCII.GetBytes(reader.ReadToEnd());
 }
```
Thanks!

**Comment by jchannon** [comment]
Would recommend making your route handler async to avoid the `.Result` :)
