### ISSUE TITLE
Add custom header in an After Hook

### ISSUE THREAD

**Issue by Matias-Barrios** [CarterCommunity/Carter#209]
Hi Guys,

I am trying to add a custom header to each response my app is returning. I added this code in the **startup.cs** file but I'm getting an error stating **the response already started** :

```
 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
       {
           app.UseExceptionHandler("/errorhandler");
           app.UseCarter(new CarterOptions(after: ctx => HeaderInjector(ctx)));
       }
       public Task HeaderInjector(HttpContext context)
       {
           context.Response.Headers.Add("x-gamecentral-received", "game1");
           return Task.CompletedTask;
       }
```

Am I doing something wrong?

**Comment by jchannon** [comment]
Afraid not, if you have returned a response we don't wrap it then issue a
response, ASP.NET Core spots response has started and won't allow
modification, best bet is to set a response header in the Before hook

**Comment by Matias-Barrios** [comment]
Thanks for your response. Now my code changed to this :

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseExceptionHandler("/errorhandler");
            app.UseCarter(new CarterOptions(before: ctx => HeaderInjector(ctx)));

        }
        private Task<bool> HeaderInjector(HttpContext ctx)
        {
            ctx.Request.Headers["x-gamecentral-received"] = "game1";
            return Task.FromResult(true);
        }
``` 

And I don't get any errors anymore. But I don't see the header on the response.
I have tested this in a simple endpoint that basically replies with "Healthy!"

**Comment by jchannon** [comment]
You've set the request headers not the response ;)

**Comment by Matias-Barrios** [comment]
@jchannon Thanks so much! Now its working!

**Comment by jchannon** [comment]
No probs :)
