### ISSUE TITLE
Possibility to choose json.net over system.text.json

### ISSUE THREAD

**Issue by wastaz** [CarterCommunity/Carter#227]
The new system.text.json is faster, but it is quite lacking in what it can actually do. I have several models which requires features that system.text.json does not support and I would really like to be able to plug in json.net again :)

**Comment by JoeStead** [comment]
It's happening: https://github.com/CarterCommunity/Carter/pull/225

**Comment by bugproof** [comment]
One bad thing about this is that it forces dependency upon Newtonsoft.Json. It would be better if it was split to a separate NuGet like `Carter.Serialization.NewtonsoftJson` or something like that

**Comment by jchannon** [comment]
Agree. We'll see what happens with .Net 6 and the impact that might have

**Comment by bugproof** [comment]
And what impact should it have?

**Comment by jchannon** [comment]
Not sure at this point :)
