### ISSUE TITLE
Bind<T> and camelcase

### ISSUE THREAD

**Issue by lindsve** [CarterCommunity/Carter#228]
I'm scratching my head here, and really don't get what I'm missing here

If I have this model:
```
public class Foo
{
    public string Bar {get; set;}
}
```

and return this from an endpoint: `await httpResponse.AsJson(someInstanceOfBar);`, then it is camelcased to proper Json:
```
{
    "bar": "someValue"
}
```

But if I post the same thing back and try to use `await httpRequest.Bind<Foo>();` then it fails to deserialize due to casing differences, and I can't see any way to give `Bind<T>` any `JsonSerializerOptions`.

I'm sure it's something very obvious I'm missing here, but I fail to see it :)

**Comment by jchannon** [comment]
this has been fixed in master.

just setting up CI for .net 3.1 so there's no CI package you can use currently, obviously you can build from source if you like

**Comment by jchannon** [comment]
Please see the README for the link to the latest CI package where this is fixed
