### ISSUE TITLE
Add option to disable OpenApi feature which is enabled by default

### ISSUE THREAD

**Issue by alifxyd** [CarterCommunity/Carter#229]

**Comment by jchannon** [comment]
Is it causing issues? I’m not against adding the option though. Feel free
to add the property to the option class and return 404 if disabled in a PR?
:)

**Comment by alifxyd** [comment]
I don't want to expose the `/openapi` endpoint when there is no need for it. And it would be nice to have it configurable. As a workaround I can create a middleware to reject all the requests to it, but it's better to not map it on startup.

Okay, will try to find some time for this a bit later.

Thanks
