### ISSUE TITLE
Data binding from request does not work when letter casing is different

### ISSUE THREAD

**Issue by KimiBitanga** [CarterCommunity/Carter#236]
Issue found in Carter 5.0.0.
This is already fixed in DefaultJsonModelBinder but it is added after Carter 5.0.0 was released.
We need you to release new version with this fix.

**Comment by JoeStead** [comment]
You can a package with the latest version here: https://github.com/CarterCommunity/Carter#ci-builds which should keep you going until the next version is pushed out to nuget

**Comment by JoeStead** [comment]
The latest has been released targetting 3.1

If this is an issue you can either use an old ci build or upgrade to the latest!
