### ISSUE TITLE
Example on how to use role based identity in unit-tests

### ISSUE THREAD

**Issue by danielmoncada** [CarterCommunity/Carter#239]
Hello,

Current set of unit-tests for security appear to be around claims. Would like to see a sample surrounding 'role' based identification.

Current policy is set up as (with my UTs returning a 500 unauthorized)
```cs
      services.AddAuthorization(options =>
      {
           options.AddPolicy("LoggedIn", policy => policy.RequireRole(loggedInRoles));
      });
```

**Comment by jchannon** [comment]
Not really a direct Carter concern
