### ISSUE TITLE
Provide a view engine or at least a sample if it already exists

### ISSUE THREAD

**Issue by mika76** [CarterCommunity/Carter#242]
I see there is a carter mvc sample but it's missing the V part - does Carter provide some sort of View engine (I see nothing mentioned in the repo or in the issues), if not is it planned? if so could you provide a sample?

**Comment by jchannon** [comment]
It doesn’t. Razor is too tied with MVC to be separated out. We did have a
plug-in to work with handlebars which stalled but would be happy for
someone to give it a go

**Comment by mika76** [comment]
Interesting I see Nancy uses this one https://github.com/grumpydev/SuperSimpleViewEngine

**Comment by DoubleOhmSeven** [comment]
> 
> 
> I see there is a carter mvc sample but it's missing the V part - does Carter provide some sort of View engine (I see nothing mentioned in the repo or in the issues), if not is it planned? if so could you provide a sample?

Two options that work reliably.
1. You can mix MVC controllers (and their views) with Carter, use the MVC sample as base and add AddRazorPages and MapRazorPages.
2. Use RazorLight (or any other Razor compiler). It's a bit more work but easy enough to get going and better integrates with Carter routes.

**Comment by jchannon** [comment]
The plugin I mention above is here https://github.com/CarterCommunity/Carter.HtmlNegotiator/blob/master/src/HtmlNegotiator.cs

**Comment by DoubleOhmSeven** [comment]
I've been experimenting a bit more with MVC controllers and found out you can use the controllers just for the views, as long as you don't use the same route twice, such as /view in a controller and /view in a module. What works fine is /view for controller and Get/Post("/view/xyz") in the module. I'm now using a controller just to serve the views. All json stuff is done by the modules. The upside is that this is much faster than using RazorLight (response times are less than 20% of the time with RazorLight).

**Comment by jchannon** [comment]
If you'd like to send a PR to amend the CarterAndMVC sample we have, I'd love to see that - https://github.com/CarterCommunity/Carter/tree/master/samples/CarterAndMVC

**Comment by mindcrash** [comment]
With a few small adjustments (due to some breaking naming changes in .NET Core 3) you can make the HTML Negotiator work (mentioned earlier) with the latest release.

**Comment by mika76** [comment]
I also found https://github.com/lunet-io/scriban which is a text templating engine which might be able to work...

**Comment by dlwiii** [comment]
@DirkJanIT , do you have any example code using Razor?  We have a large Nancy application that we are looking to migrate over, but its view are all Razor-based.

**Comment by PhyxionNL** [comment]
I'm also using Carter with built-in Razor. You'll basically need to add the standard MVC code to Startup (https://github.com/CarterCommunity/Carter/blob/master/samples/CarterAndMVC/Startup.cs), for example:
https://gist.github.com/PhyxionNL/61cedf66cf704f55eff985ceac0c0199

This way you can use controllers for views and modules for the rest (json/xml/whatever you'd like to serve). You obviously cannot use the same route twice, so you need to keep track of which routes are used. It's probably possible to return a view from a carter module with a bit of code, but I just use a controller for serving the views.
