### ISSUE TITLE
Form Binding logic is extremely inefficient

### ISSUE THREAD

**Issue by davidfowl** [CarterCommunity/Carter#243]
Bytes -> Dictionary -> Another Dictionary -> JSON string -> Object

https://github.com/CarterCommunity/Carter/blob/2dfc291a518d7d9e2febd78b203538e72ea9306e/src/Carter/Modelbinding/BindExtensions.cs#L39-L67

**Comment by jchannon** [comment]
I knew this when first written and never gone back to look at it
unfortunately

**Comment by davidfowl** [comment]
It would be good to understand if people are using  this feature of Carter. Especially if it’s mostly used for backend APIs maybe you can eventually kill the feature

**Comment by jchannon** [comment]
Yeah not entirely sure on usage numbers. Hard to calculate that. It was
added as someone asked for it I think but would assume most is json bodies

**Comment by jchannon** [comment]
Have killed the feature. Happy to take a performant implementation to add back in
