### ISSUE TITLE
Add logging in OpenAPI

### ISSUE THREAD

**Issue by jchannon** [CarterCommunity/Carter#245]
If something fails for example https://github.com/CarterCommunity/Carter/blob/master/src/Carter/OpenApi/CarterOpenApi.cs#L30 we need to log why.

Might be worth logging other areas to highlight what's going on in the output generation

**Comment by jeffdoolittle** [comment]
I'll take this one also. Any other places you want logging?

**Comment by jchannon** [comment]
Not off the top of my head but feel free to take a look around the code
base and add any you think would be helpful.

Saw your earlier tweet and glad you’re here! I’m sure there’s lots you can
teach us 😄so you have nothing to worry about. Have fun!

**Comment by jchannon** [comment]
Also just realised wrong Jeff 😂😂

Point still stands though 😄

**Comment by jeffdoolittle** [comment]
No worries. Assign it to me and I'll dive in over the next few days.

**Comment by jchannon** [comment]
Carter 6 uses ASP.NET Core OpenAPI
