### ISSUE TITLE
Carter seems to ignore UsePathBase

### ISSUE THREAD

**Issue by phillip-haydon** [CarterCommunity/Carter#247]
```
app.UseRouting();
app.UsePathBase("/api");
app.UseEndpoints(builder => builder.MapCarter());
```

When using Carter with a base path, it seems to ignore it. Do I have to go define this as a base module?

**Comment by jchannon** [comment]
Correct.

Didn’t know if that middleware. Could add some code to check if it’s set
but a base module will work for now

**Comment by phillip-haydon** [comment]
I believe it's built in. Doesn't need any special dependency. 

It's strange tho, as it requires the route to begin with `/` but routes in ASP.NET cannot start with `/`

**Comment by jbogard** [comment]
@jchannon Looks like this still ignores `UsePathBase` which we use for reverse proxies, do we need to create a base module to set a base path?

**Comment by jbogard** [comment]
Yah it's .NET 6. I'll poke around

**Comment by jchannon** [comment]
My guess with minimal apis is that you'll have to be explicit in the route
definition which kinda sucks

**Comment by jbogard** [comment]
It's not Carter, it's a thing with minimal routing:

https://github.com/dotnet/aspnetcore/issues/38448

Adding the call to `UseRouting` fixed for me:

```csharp
app.UsePathBase("/api");
app.UseRouting();
app.MapCarter();
```
