### ISSUE TITLE
Custom Action on After hook

### ISSUE THREAD

**Issue by Jaxelr** [CarterCommunity/Carter#248]
I currently have a small library i am trying to use for Caching responses, the way the behavior is defined is somewhat similar to the RequiresAuthentication extension method:

```c#
        public static void EnableCaching(this CarterModule module)
        {
            module.Before += async (ctx) => await CheckCache(ctx);
            module.After = async (ctx) => await SetCache(ctx);
        }
```

The problem i'm facing is that the After Delegate has a protected set, which means i cannot set the module.After outside of the CarterModule class. I'm sure there's a reasoning behind this, is there an alternative for me to do this in a more general fashion ?

**Comment by JoeStead** [comment]
It may be better purposed as middleware before Carter is even hit, so you will do something along the lines of 

```
var cacheResult = await CheckCache(ctx);

if(cacheResult != null)
{
next(); //next here is the carter middleware
}

await SetCache(ctx);
```

So doing it at the ASP.NET Core middleware level rather than carter.

Hope this helps a bit

**Comment by Jaxelr** [comment]
Thanks @JoeStead

**Comment by JoeStead** [comment]
No problem, let me know if you want any help with that middleware
