### ISSUE TITLE
Carter on .net framework

### ISSUE THREAD

**Issue by karm435** [CarterCommunity/Carter#252]
Hi,

 We are currently using Nancy in our project and as that project has been archived, we are thinking to move away from it. We are using .net 4.7.2. 

In the description it is mentioned that Carter is layer of extensions over aspnetcore. Is it possible to use this framework on .net full framework?

Thank you.

**Comment by karm435** [comment]
It cannot be. Just did a quick test with .net framework wep app and it did not install.

**Comment by jchannon** [comment]
Carter targets netcoreapp
