### ISSUE TITLE
CarterOptions() before lambda expression on 5.1.0

### ISSUE THREAD

**Issue by heitor481** [CarterCommunity/Carter#253]
Hi all

On previous carter version, we had the possibility to, inside the Configure method of Startup.cs create a lambda expression inside the app.UserCarter() to inject something on the header response of every call to our api.

So basically the call was something like that:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env) 
{
   app.UseCarter(new CarterOptions(before: ctx => Inject(ctx)))
}

private Task<bool> Inject(HttpContext ctx) 
{
   ctx.Response.Headers["our-api-header"] = ((int)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds).ToString();
 return Task.FromResult(true);
}
```

This is something that was possible on old version of carter. But, on the new one, I didn't see any option like that. So, my question is: is that something like that on Carter 5.1.0? Or it was removed?

Thanks in advanced

**Comment by jchannon** [comment]
This was done on v5.0.0 and was a breaking change
https://github.com/CarterCommunity/Carter/pull/149

We recommend that you use middleware to do this:

app.Use(async (context, next) =>
        {
            // Do work that doesn't write to the Response.
            await next.Invoke();
            // Do logging or other work that doesn't write to the Response.
        });

**Comment by heitor481** [comment]
Got it John!

Thanks a lot for the clarification about that issue.

I'm closing this thread.
