### ISSUE TITLE
API Version hardcoded in SwaggerUI to 3.0.0

### ISSUE THREAD

**Issue by aespinoza** [CarterCommunity/Carter#255]
Is there a a reason why the API version is hard coded to 3.0.0 ?

The line I am referring is this: https://github.com/CarterCommunity/Carter/blob/33e22c6d3f7f5daa0aa63673749ff79d70845993/src/Carter/OpenApi/CarterOpenApi.cs#L33

It is my understanding that this version is the API version not the OpenAPI Spec Version.

**Comment by JoeStead** [comment]
The interesting line is:

https://github.com/CarterCommunity/Carter/blob/33e22c6d3f7f5daa0aa63673749ff79d70845993/src/Carter/OpenApi/CarterOpenApi.cs#L341

That should be setting the `openapi` property at the document level, which doesn't seem to exist on the type.

**Comment by aespinoza** [comment]
Thank you man. I was going to fix it, but I wanted to make sure I understood the issue before committing any changes.

**Comment by jchannon** [comment]
@aespinoza thanks for spotting this! 👍
