### ISSUE TITLE
Nested CarterModules are not found when using Default AddCarter()

### ISSUE THREAD

**Issue by ggmueller** [CarterCommunity/Carter#259]
When using the following configuration in the Startup: `services.AddCarter()` Carter does not consider Nested Classes as modules that it configures.

Registering nested classes explicitly works.

It seems like this is due to this LINQ condition in the code:

```csharp
modules = assemblies.SelectMany(x => x.DefinedTypes
                    .Where(t =>
                        !t.IsAbstract &&
                        typeof(CarterModule).IsAssignableFrom(t) &&
                        t != typeof(CarterModule) &&
                        t.IsPublic
                    ));
```
In a quick test changing this piece of code to also consider type with `t.IsNestedPublic` in the debugger also registered the nested classes.

Is the restriction of types to only outer types intended?

**Comment by JoeStead** [comment]
No reason that I'm aware of. It's a bit of an interesting setup, but if it works... it works

**Comment by jchannon** [comment]
Carter 6 will use ICarterModule

**Comment by yegorandrosov** [comment]
still does not work, DependencyContextAssemblyCatalog.GetAssemblies does not include nested classes
