### ISSUE TITLE
Unable to bind a model with LocalDate property

### ISSUE THREAD

**Issue by Deilan** [CarterCommunity/Carter#275]
If a model has a property `LocalDate` ([Noda Time](https://github.com/nodatime/nodatime)), `Bind<T>` silently creates a new instance of `T` with all properties initialized with their default values.

Reproduced with `DefaultJsonModelBinder`, but not `NewtonsoftJsonModelBinder`

**Comment by jchannon** [comment]
What is the JSON you are POSTing

**Comment by ritasker** [comment]
Did using the `NewtonsoftJsonModelBinder ` resolve your issue?
You mention using Noda Time types, you may need to create a custom model binder using [NodaTime.Serialization.SystemTextJson](https://www.nuget.org/packages/NodaTime.Serialization.SystemTextJson) this will register all the type converters required for serialising the Noda Time types.

For example: https://gist.github.com/ritasker/fc5cfbfb82bcf28534d3ac1c3bd46ea7

**Comment by Deilan** [comment]
@ritasker Thank you very much for your help! You are right.

For some reason even just switching to Carter's `NewtonsoftJsonResponseNegotiator` and `NewtonsoftJsonModelBinder` was enough:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddCarter(configurator: configurator =>
    {
        configurator.WithResponseNegotiator<NewtonsoftJsonResponseNegotiator>();
        configurator.WithModelBinder<NewtonsoftJsonModelBinder>();
    });
}
```

**Comment by JoeStead** [comment]
Glad using a different JSON deserialiser helped

**Comment by jnysteen** [comment]
> Did using the `NewtonsoftJsonModelBinder ` resolve your issue? You mention using Noda Time types, you may need to create a custom model binder using [NodaTime.Serialization.SystemTextJson](https://www.nuget.org/packages/NodaTime.Serialization.SystemTextJson) this will register all the type converters required for serialising the Noda Time types.
> 
> For example: https://gist.github.com/ritasker/fc5cfbfb82bcf28534d3ac1c3bd46ea7

I just hit this issue today and tried fixing it by using this gist, but I am unable to find both the `WithModelBinder` extension method and the `ModelBinderBase` class. 

Next, I tried using the solution suggested in https://github.com/CarterCommunity/Carter/issues/275#issuecomment-789805687, but I again am missing the `WithModelBinder` extension method and now the `NewtonsoftJsonModelBinder`.

I guess that these things existed in past versions of Carter - any idea on how to fix it in the current version?

**Comment by jchannon** [comment]
This might help. It might not.

https://stackoverflow.com/questions/69850917/how-to-configure-newtonsoftjson-with-minimalapi-in-net-6-0

**Comment by jnysteen** [comment]
> This might help. It might not. https://stackoverflow.com/questions/69850917/how-to-configure-newtonsoftjson-with-minimalapi-in-net-6-0
> […](#)

Thanks, that link led me down the right path.
The `JsonOptions` used when deserialising request contents can now be configured to work for NodaTime types like this:

```csharp
...
using Microsoft.AspNetCore.Http.Json;
using NodaTime.Serialization.SystemTextJson;
...

services.AddCarter();
services.Configure<JsonOptions>(opt => opt.SerializerOptions.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb));
