### ISSUE TITLE
Unable to find package Microsoft.Extensions.DependencyModel with version (>= 6.0.0-rtm.21518.12)

### ISSUE THREAD

**Issue by isaacOjeda** [CarterCommunity/Carter#280]
Since version 6-rc2 i'm getting this error when i'm trying to use Carter on .NET 6

This was added in this commit [640e105](https://github.com/CarterCommunity/Carter/commit/640e105d200f15db1241f53383fc39e5b2b321f2) but it's using a custom NuGet feed thus it can't be resolved with nuget.org.

The Nuget feed configured in Carter is `<add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />` 

No problem to add this feed while i'm doing experiments with carter, but in production i think it should use nuget.org as usual.

Error:
```
Unable to find package Microsoft.Extensions.DependencyModel with version (>= 6.0.0-rtm.21518.12)
  - Found 64 version(s) in nuget.org [ Nearest version: 6.0.0-rc.2.21480.5 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

**Comment by jchannon** [comment]
Try rc3

**Comment by isaacOjeda** [comment]
Same result 😅
![image](https://user-images.githubusercontent.com/2521593/140615876-e189fa68-01e7-4063-b83e-672fa3475613.png)

**Comment by jchannon** [comment]
MS probably changing their feed as they develop and get ready for the .NET 6 release next week. Once it's out next week it should be fine. If you're in a rush, fork the repo and update it and run dotnet pack to create a nupkg

**Comment by isaacOjeda** [comment]
I'll wait until the release and then close this issue, thank you for your response

**Comment by isaacOjeda** [comment]
.NET 6 released, everything working now. Thanks

**Comment by jchannon** [comment]
I've pushed some changes to the net6 branch which will fix it but not
released anything yet onto nuget/feedz
