### ISSUE TITLE
can't find much on IResponseNegotiator docs or samples

### ISSUE THREAD

**Issue by drdamour** [CarterCommunity/Carter#290]
i'm intrigued by this idea as i think it'll help me return different representations for accept: application/hal+json vs application/vnd.mason+json for example, but i couldn't find much on it.  hoping there's some stuff out there i'm missing

**Comment by jchannon** [comment]
You are correct in your assumption and correct in a lack of samples which
will need fixing in the future. For now I can point you to the tests

https://github.com/CarterCommunity/Carter/blob/main/test/Carter.Tests/ContentNegotiation/ResponseNegotiatorTests.cs

**Comment by jchannon** [comment]
No, I think the tests are pretty clear

**Comment by drdamour** [comment]
hm, not to be flippant, but based on what?  have people successfully  created em from the tests?

**Comment by jchannon** [comment]
Well you just create a class and implement the interface that has 2 methods. Here's an example:

https://github.com/CarterCommunity/Carter/blob/main/test/Carter.Tests/ContentNegotiation/ResponseNegotiatorTests.cs#L113

It says this negotiator will be used when the accept header is foo/bar and then in the Handle method it's up to you how you write the response.
