### ISSUE TITLE
Possible startup performance issue

### ISSUE THREAD

**Issue by yavorfingarov** [CarterCommunity/Carter#315]
Hello! 

I ran some benchmarks and got surprising results about the startup performance of Carter. Here is the data: https://github.com/yavorfingarov/Reprise#startup 

It might be worth to consider this for a future improvement. If you think that there might be a problem with my benchmarks (https://github.com/yavorfingarov/Reprise/tree/master/tests), please let me know.

**Comment by jchannon** [comment]
Do you have a breakdown of where the time is taken? My guess is Carter
assembly scanning and registering types.

**Comment by yavorfingarov** [comment]
Thanks for pointing me to the problem! 

Reprise and FastEndpoints do an assembly scan too, but Carter scans referenced assemblies as well, so in my case it does considerably more work that the others. I fixed the issue and, as I initially expected, Carter has only a tiny bit slower startup than the Minimal APIs. You can check the updated benchmarks here: 

https://github.com/yavorfingarov/Reprise#startup

**Comment by jchannon** [comment]
You can possibly speed it up more by manually specifying what module to
register and what assembly to scan in the AddCarter call

**Comment by yavorfingarov** [comment]
Yeah, I did exactly that, thanks.

**Comment by jchannon** [comment]
Just looked. I reckon you could speed it up a tiny bit more too by
specifying the module and validator and exclude response negotiators in the
second arg to AddCarter.

Will try a PR tomorrow if I remember.

**Comment by yavorfingarov** [comment]
Thanks for pointing that out! I will exclude the negotiators in the next release. Since both Reprise and FastEndpoints are doing a scan for endpoints and validators, I think specifying those in the Carter implementation might be a bit unfair. Please correct me if I'm wrong.
