### ISSUE TITLE
[Question] Is it possible to do property injection on a CarterModulse version 7 and autofac

### ISSUE THREAD

**Issue by samatstariongroup** [CarterCommunity/Carter#318]
Hi,

I am having a hard time getting property injection to work using a class that implements ICarterModule and Autofac. Constructure injection is working just fine. Anything special i need to do to get it to work?

- Carter version 7.0.1
- Autofac.Extensions.DependencyInjection version 8.0.0

**Comment by jchannon** [comment]
Not something I’ve ever tried
