### ISSUE TITLE
How to configure my filters 

### ISSUE THREAD

**Issue by xts-velkumars** [CarterCommunity/Carter#321]
Good day, 

How to configure my filters in one place. 

I don't want to add AddEndpointFilter in every method.

**Comment by jchannon** [comment]
In a constructor of your module you can do something like this

this.Before = context =>
{
var logger = context.HttpContext.RequestServices.GetRequiredService<ILogger<
DirectorsModule>>();
logger.LogDebug("Before");
return null;
};
this.After = context =>
{
var logger = context.HttpContext.RequestServices.GetRequiredService<ILogger<
DirectorsModule>>();
logger.LogDebug("After");
};

**Comment by jchannon** [comment]
In a constructor of your module you can do something like this

```csharp
this.Before = context =>
{
var logger = context.HttpContext.RequestServices.GetRequiredService<ILogger<
DirectorsModule>>();
logger.LogDebug("Before");
return null;
};
this.After = context =>
{
var logger = context.HttpContext.RequestServices.GetRequiredService<ILogger<
DirectorsModule>>();
logger.LogDebug("After");
};
```
