### ISSUE TITLE
[QUESTION] Any sample code using .WithOpenApi

### ISSUE THREAD

**Issue by obiiswise** [CarterCommunity/Carter#322]
Hi!

Do you have any sample code using the .WithOpenApi on endpoints like .MapGet or .MapPost?  I'd like to be able to configure our endpoints so Swagger will pull in the various response types, etc.

Thank you!

**Comment by jchannon** [comment]
Try here -
https://github.com/CarterCommunity/Carter/blob/main/samples/CarterSample/Features/Actors/ActorsModule.cs#L12
