### ISSUE TITLE
Endpoints Not Visible in EndpointsApiExplorer

### ISSUE THREAD

**Issue by johnholliday** [CarterCommunity/Carter#326]
Declaring minimal API endpoints in a Carter module hides them from the EndpointsApiExplorer.

**Comment by jchannon** [comment]
Does this sample app work for you?

https://github.com/CarterCommunity/Carter/blob/main/samples/CarterSample/Program.cs

**Comment by johnholliday** [comment]
The problem is that the EndpointsApiExplorer requires literal path strings.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jchannon** [comment]
I don’t understand sorry

**Comment by johnholliday** [comment]
The problem is not with Carter.  The EndpointsApiExplorer cannot recognize paths that are declared with const or static strings.  They have to be literal strings.  In other words...

This works

```csharp
public class ActorsModule : ICarterModule
{
  public void AddRoutes(IEndpointRouteBuilder app)
  {
    app.MapGet("/actors", GetAllActors).WithName("GetActors");
  }
}
```

This does not work.  The Api explorer view will be empty.

```csharp
public class ActorsModule : ICarterModule
{
  public static string ActorsRoute = "/actors";
  public void AddRoutes(IEndpointRouteBuilder app)
  {
    app.MapGet(ActorsRoute, GetAllActors).WithName("GetActors");
  }
}
```
