### ISSUE TITLE
Removed support to apply endpoint conventions globally

### ISSUE THREAD

**Issue by mikeolasz** [CarterCommunity/Carter#329]
With [this](https://github.com/CarterCommunity/Carter/commit/aaa09b59d444e6528c12245fc144d67a0d3691a7#diff-ff4fe2902bfc85b0e2bba954c7b04ac67fb33dbd0c34ea6319c9ae7182dba825L28) change the return type MapCarter was changed and it's no longer _IEndpointConventionBuilder_. It would have been really nice to put RequireAuthorization on all endpoints. 

The discussion [here](https://github.com/CarterCommunity/Carter/issues/207) introduced a nice solution and it's partly removed now. Is there any chance it's gonna be reintroduced or updated?

Currently I don't see any way to apply conventions for multiple endpoints only one-by-one. Could you suggest a solution for this?

**Comment by jchannon** [comment]
https://github.com/CarterCommunity/Carter/blob/main/samples/CarterSample/Features/Directors/DirectorsModule.cs#L10

**Comment by mikeolasz** [comment]
That's unfortunate. It would've been really nice if you could use it similarly to ASP.NET Core's MapControllers etc. Thanks!
