### ISSUE TITLE
Unable to change the field of the response data body to uppercase

### ISSUE THREAD

**Issue by Fengtao1314520** [CarterCommunity/Carter#332]
when i use our library, i had set

`builder.Services.AddCarter();`
`builder.Services.AddControllers() .AddJsonOptions(options => options.JsonSerializerOptions.PropertyNamingPolicy = null);
`
but output still keep lowcase for first word, like this
` "userStatus": "active",`
I need uppercase
` "UserStatus": "active",`

I have to changed respone code like this 
`return Results.Json(result, new JsonSerializerOptions
        {
            PropertyNamingPolicy = null
        });`

it  can be work, but not i hoped method, i think must have other method can solve it.

**Comment by jchannon** [comment]
Create your own IResponseNegotiator with the settings you want, Carter will
register it in DI automatically

https://github.com/CarterCommunity/Carter/blob/main/src/Carter/Response/DefaultJsonResponseNegotiator.cs

**Comment by jchannon** [comment]
You could also define json serializer options using the below, either approaches will work

```
x.ConfigureHttpJsonOptions(jsonOptions =>
                        {
                            jsonOptions.SerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.KebabCaseUpper;
                        });
```
