### ISSUE TITLE
Trying to get swagger working with my project.

### ISSUE THREAD

**Issue by shawnarvin** [CarterCommunity/Carter#335]
The swagger UI page does not show any operations after installing and configuring swagger using the Swashbuckle.AspNetCore project.
![screenshot](https://github.com/CarterCommunity/Carter/assets/14608669/d4ccf7a5-0595-4691-9926-bc65391fd0f5)

**Comment by jchannon** [comment]
Does this help.
https://github.com/CarterCommunity/Carter/blob/main/samples/CarterSample/Features/Actors/ActorsModule.cs

**Comment by idusortus** [comment]
Similar issue here. I followed your suggestion, @jchannon, but I was unable to get the endpoints to show up in SwaggerUI.

This works fine:
```csharp
(Program.cs)
builder.Services.AddSwaggerGen();
...
CreateArticle.MapEndpoint(app);

(CreateArticle.cs)
public static void MapEndpoint(this IEndpointRouteBuilder endpoints)
  {
      endpoints.MapPost("api/articles", async (CreateArticle.Command command, ISender sender) =>
      {
          var result = await sender.Send(command);
          if (result.IsFailure)
          {
              return Results.BadRequest(result.Error);
          }
          
          return Results.Ok(result.Value);
      });
  }
```

This does not:
```csharp
(Program.cs)
...
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Description = "Carter Sample API",
        Version = "v1",
        Title = "A Carter API to manage Actors/Films/Crew etc"
    });
    
    options.DocInclusionPredicate((s, description) =>
    {
        foreach (var metaData in description.ActionDescriptor.EndpointMetadata)
        {
            if (metaData is IIncludeOpenApi) return true;            
        }
        return false;
    });
});
...
builder.Services.AddCarter();
...
app.MapCarter();

(CreateArticle.cs)
  public class Endpoint : ICarterModule
  {
      public void AddRoutes(IEndpointRouteBuilder app)
      {
          app.MapPost("api/articles", async (CreateArticle.Command command, ISender sender) =>
          {
              var result = await sender.Send(command);
              if (result.IsFailure)
              {
                  return Results.BadRequest(result.Error);
              }
              return Results.Ok(result.Value);
          })
          .WithTags("SomeTag")
          .WithName("Something")
          .IncludeInOpenApi();
      }
  }
```


I haven't dug into the issue, was looking around for solutions and came across this.  End of my night, I'll look again tomorrow to check for obvious oversights on my part.

Happy to push a repro repo if it helps.

Thanks!

**Comment by idusortus** [comment]
Whoops... I had the **Endpoint : ICarterModule** class nested within a static class. 

The RouteEndpoint defined in my : ICarterModule class now appears as expected in the SwaggerUI.

Note that it works fine without the inclusion of .IncludeInOpenApi();

Thanks!

**Comment by jchannon** [comment]
I can't reproduce this. If you run the CarterSample app you'll see CastMembers doesn't appear in SwaggerUI. Once you add `IncludeInOpenApi` they appear. 

If you'd like to push up a repro then let me know 👍
