### ISSUE TITLE
[Question] What is the best way to return a HTTP Api response using Carter?

### ISSUE THREAD

**Issue by jeffward01** [CarterCommunity/Carter#354]
Hello,

I am curious what the recommended method is to return http response data using Carter?

Carter Examples use this `Negotiate()`:

```csharp
 var result = req.Validate<Actor>(actor);

                if (!result.IsValid)
                {
                    res.StatusCode = 422;

                   // Is this the recommended way?
                    await res.Negotiate(result.GetFormattedErrors());
                    return;
                }
```

However, this also works, and I have seen some examples online of other user's using carter, while using this response type from `Microsoft.AspNetCore.Http`:

```csharp
         var validationResult = await req.ValidateAsync(command);
                
                if (!validationResult.IsValid)
                {

                    // Or is this fine also?
                    return Results.ValidationProblem(validationResult.GetValidationProblems(),
                        statusCode: 422);
                }
```

Is there a difference between the two ways of returning an HTTP Response? Using `Negotiate()`, versus using the `Results.XXX` from `Microsoft.AspNetCore.Http`

Thanks all

**Comment by jchannon** [comment]
Negotiate is a way to tell Carter to look for a ResponseNegotiator to
represent the result data as the conte t type the client has asked for in
the Accept header.

I believe using Result.Ok(myDataObject) always forces it to use the json
serializer.

You can also just do return myDataObject too
