### ISSUE TITLE
MinimalOpenAPI versioning with Carter

### ISSUE THREAD

**Issue by senal** [CarterCommunity/Carter#359]
Hi,
I've been trying to get the versioning enabled for my minimal api.
I was following a sample project available from Microsoft (`https://github.com/dotnet/aspnet-api-versioning/blob/main/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs`)

Please find the attached sample project.
[carter-minimal.zip](https://github.com/user-attachments/files/16333439/carter-minimal.zip)

When I configure endpoints in the program file. The Swagger document generates both versions without any issues
swagger doc
version one
<img width="406" alt="image" src="https://github.com/user-attachments/assets/6315ee8d-4ca2-43f8-a8ff-021af1474c25">
version two
<img width="404" alt="image" src="https://github.com/user-attachments/assets/cbc3d356-e607-42ff-879b-00b3ec3b2905">

```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddProblemDetails();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddApiVersioning(o =>
{
    o.ReportApiVersions = true;
}).AddApiExplorer(o => {
    o.GroupNameFormat = "'v'VVV";
    o.SubstituteApiVersionInUrl = true;
});

builder.Services.AddTransient<IConfigureOptions<SwaggerGenOptions>, ConfigureSwaggerOptions>();
builder.Services.AddSwaggerGen(o => o.OperationFilter<SwaggerDefaultValues>());

var app = builder.Build();

var vs = app.NewApiVersionSet().Build();
app.MapGet("/hello1", () => Results.Ok($"Hello")).WithApiVersionSet(vs).HasApiVersion(1.0);
app.MapGet("/hello2", () => Results.Ok($"Hello")).WithApiVersionSet(vs).HasApiVersion(2.0);


if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(o => 
    {
        var descriptions = app.DescribeApiVersions();
        foreach (var description in descriptions)
        {
            var url = $"/swagger/{description.GroupName}/swagger.json";
            var name = description.GroupName.ToUpperInvariant();
            o.SwaggerEndpoint(url, name);
        }
    });
}

app.UseHttpsRedirection();


app.Run();

```

However, When I defined my endpoints with `ICarterModule` with `ApiVersionSet` I couldn't get the API document generated as in the previous scenario.

Login version 1
```
    public class Login : ICarterModule
    {
        public void AddRoutes(IEndpointRouteBuilder app)
        {
            var vs = app.NewApiVersionSet("hello").Build();
            app.MapGet("/hello", () => Results.Ok($"Hello"))
                .WithApiVersionSet(vs)
                .WithOpenApi()
                .HasApiVersion(1.0);
        }
    }
}
```
Login version 2
```
    public class Login : ICarterModule
    {
        public void AddRoutes(IEndpointRouteBuilder app)
        {
            var sa = app.NewApiVersionSet("hello").Build();
            app.MapGet("/hello", () => Results.Ok())
                .WithApiVersionSet(sa)
                .WithOpenApi()
                .HasApiVersion(2.0);
        }
    }
```
Will someone help me to understand the wrong I have done here.

Have I missed any additional configurations?
Does Carter support the API versioning?

Can someone help me to get the API version working with Carter?

Thanks & Regards

**Comment by edwardmcleodjones** [comment]
I just ran into this as well.

My issue was I had:
```csharp
        app.MapCarter();
```
**below** the call to:
```csharp
        app.UseSwagger();
        app.UseSwaggerUI...
```

Moving it **above** the `UseSwagger` options fixed it, e.g.

```csharp
        app.MapCarter();
        app.UseSwagger();
        app.UseSwaggerUI...
```

**Comment by senal** [comment]
@edwardmcleodjones ,
That worked! Thank you very much.
