### ISSUE TITLE
JSON Serialization Options

### ISSUE THREAD

**Issue by aplocher** [CarterCommunity/Carter#366]
Hey everyone, 

Using Carter 8.2.1.

I'm running into an issue setting global Json Serialization options for all my APIs. I would like my integer-backed-enums to get serialized with only their names (so integers/IDs don't get exposed to the consumer).

Example of an enum that I would like serialized to remove the integers:

```
public enum ProjectTypeEnum
{
    Bid = 1,
    ChangeOrder = 2,
    Master = 3,
    (etc)
}
```

I've added this code to my Startup:

```
var jsonEnumSerializationConverter = new JsonStringEnumConverter(allowIntegerValues: false);

services.Configure<JsonOptions>(options =>
{
    options.JsonSerializerOptions.Converters.Add(jsonEnumSerializationConverter); // Serialize enums as strings
});
```

This will make my swagger.json generate enums correctly:

```
...
          "ProjectNumberSchemeDto": {
                "type": "object",
                "properties": {
                    "projectType": {
                        "$ref": "#/components/schemas/ProjectTypeEnum"
                    },
                    "prefix": {
                        "type": "string",
                        "nullable": true
                    },
                    "suffix": {
                        "type": "string",
                        "nullable": true
                    }
                },
                "additionalProperties": false
            },

...

            "ProjectTypeEnum": {
                "enum": [
                    "Bid",
                    "ChangeOrder",
                    "Master",
                    "etc",
                ],
                "type": "string"
            }
```

However Carter still output my API responses like this:

```
"projectNumberSchemes": [
    {
      "projectType": 1,
      "prefix": null,
      "suffix": null
    },
    {
      "projectType": 4,
      "prefix": null,
      "suffix": null
    },
    {
      "projectType": 3,
      "prefix": null,
      "suffix": null
    },
```

`projectType` should be "Bid", "ChangeOrder", etc - not 1, 4, 3.

I've read about (and tried using) Response Negotiators but those seem to require you to call Response.Negotiate explicitly on each API method. 

Is there a way to apply Json Serialization options to every Carter JSON response? This is a convention that I'd like to be applied to all API methods in my project, so we don't accidentally expose the underlying integer values.

I apologize if this is the wrong place for this. I'm not sure if this is a bug or not. It seems like my code should be changing the behavior of my JSON serialization, but it's not.

Thank you.

**Comment by jchannon** [comment]
Try using
ConfigureHttpJsonOptions

That should work!

**Comment by aplocher** [comment]
Thank you, that worked! Don't know how I missed that. :)

```
services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
});
```

Now my JSON response:

```
  "projectNumberSchemes": [
    {
      "projectType": "Bid",
      "prefix": null,
      "suffix": null
    },
    {
      "projectType": "Project",
      "prefix": null,
      "suffix": null
    },
    {
      "projectType": "Master",
      "prefix": "asdfd",
      "suffix": null
    }
  ]
```
