### ISSUE TITLE
Generating URIs for Routes

### ISSUE THREAD

**Issue by dcomartin** [CarterCommunity/Carter#79]
Ability to generate a URI for another Botwin route?  Similar to Nancy.Linker.  This would likely need to give name to the route so you can resolve it.

My primary usage for this is hypermedia and returning URIs for relevant routes.

**Comment by jchannon** [comment]
https://khalidabuhakmeh.com/generate-links-to-aspnet-core-map-endpoints nerd sniping @khalidabuhakmeh

**Comment by jchannon** [comment]
I think you can now use the asp.net core link generator https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.routing.linkgenerator?view=aspnetcore-8.0

Example usage - https://poornimanayar.co.uk/blog/minimal-apis-and-hateoas/

Let me know what you think
