### ISSUE TITLE
Renaming to Carter

### ISSUE THREAD

**Issue by jchannon** [CarterCommunity/Carter#92]
Thinking of renaming Botwin to Carter.

Consensus seems to be that Botwin, whilst I think is genius, and as a benevolent dictator you cannot disagree with me, is confusing some folks as they think it's a Bot framework for Windows so after too many hours thinking about it I've come up with Carter.

Carter comes from the surname of Jay-Z (Shawn Carter) and in his song Empire State of Mind he sings "I'm the new Sinatra". Sinatra is a web framework which inspired Nancy which heavily inspired Botwin.

Unless there is any real objection like people think this is a library for giving instructions on how to cart their mother in law away ("cart - her") we'll rename this in the coming few weeks.

Let me know what you think

**Comment by aarondandy** [comment]
You could also say Carter is the flyest kid in the block. I think it's a fine name. Anything that doesn't make me think of botflies...

**Comment by pgermishuys** [comment]
I like it @jchannon!

**Comment by serialseb** [comment]
The Jay-Z of web frameworks? :-D

**Comment by jchannon** [comment]
I've got 99 problems but HTTP ain't one

**Comment by serialseb** [comment]
Well... You *are* based off HttpAbstractions... :trollface:

**Comment by jchannon** [comment]
I've got 99 problems and adoption is another

**Comment by chrissie1** [comment]
I still think ChrisTheAwesome would get you the most exposure and Karma.

**Comment by JoeStead** [comment]
Need a basketball-themed logo because Coach Carter is good.

**Comment by jchannon** [comment]
Closed with #95

**Comment by jchannon** [comment]
Icon is here https://github.com/CarterCommunity/Media/raw/master/carterlogo.png
